apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: postgresql-operator.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: postgresql-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-postgresql-operator/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: postgresql-operator.packages.kadras.io
spec:
  categories:
  - database
  displayName: postgresql-operator
  longDescription: CloudNativePG is a Kubernetes operator that covers the full lifecycle
    of a PostgreSQL database cluster with a primary/standby architecture, using native
    streaming replication.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: CloudNativePG is a Kubernetes operator that covers the full lifecycle
    of a PostgreSQL database cluster.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-postgresql-operator
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: postgresql-operator
spec:
  packageRef:
    refName: postgresql-operator.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
